export const GET_GIFs_REQUEST = 'GET GIFS REQUEST'
export const GET_GIFs_FAILURE = 'GET GIFS FAILURE'
export const GET_GIFs_SUCCESS = 'GET GIFS SUCCESS'

export const SHOW_IMAGE = 'SHOW IMAGE'
export const HIDE_IMAGE = 'HIDE IMAGE'